#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri May 23 02:30:27 +07 2025
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L blk_mem_gen_v8_4_8 -L fifo_generator_v13_2_10 -L util_vector_logic_v2_0_4 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_input_o_arbiter_behav xil_defaultlib.tb_input_o_arbiter xil_defaultlib.glbl -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L blk_mem_gen_v8_4_8 -L fifo_generator_v13_2_10 -L util_vector_logic_v2_0_4 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_input_o_arbiter_behav xil_defaultlib.tb_input_o_arbiter xil_defaultlib.glbl -log elaborate.log

