#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri May 23 01:56:58 +07 2025
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_input_o_arbiter_behav -key {Behavioral:sim_1:Functional:tb_input_o_arbiter} -tclbatch tb_input_o_arbiter.tcl -protoinst "protoinst_files/input_0_arbiter.protoinst" -view /home/socone/Documents/DATN/code/router_vivado/arbiter_input_0/tb_input_o_arbiter_behav.wcfg -log simulate.log"
xsim tb_input_o_arbiter_behav -key {Behavioral:sim_1:Functional:tb_input_o_arbiter} -tclbatch tb_input_o_arbiter.tcl -protoinst "protoinst_files/input_0_arbiter.protoinst" -view /home/socone/Documents/DATN/code/router_vivado/arbiter_input_0/tb_input_o_arbiter_behav.wcfg -log simulate.log

